server:
  port: 8080
  servlet:
    context-path: /zipkok


spring:
  application:
    name: zipkok
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://132.145.98.236:3306/zipkok?useUnicode=true&characterEncoding=utf8mb4
    username: zipkok
    password: 1234
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  # Static Resource ??
  web:
    resources:
      static-locations:
        - classpath:/static/
      add-mappings: true
  mvc:
    static-path-pattern: /resources/**

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.kosmo.zipkok.dto
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.kosmo.zipkok: debug

jwt:
  secret: your-secret-key
  expiration: 3600000

redis:
  host: localhost
  port: 6379