server:
  port: 8080
  servlet:
    context-path: /zipkok


spring:
  application:
    name: zipkok
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://132.145.98.236:3306/zipkok?useUnicode=true&characterEncoding=utf8mb4
    username: zipkok
    password: 1234
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  web:
    resources:
      static-locations:
        - classpath:/static/

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.kosmo.zipkok.dto
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.kosmo.zipkok: debug

jwt:
  secret: "zipkok-jwt-secret-key-2025-super-secure-random-string-with-at-least-64-characters-for-hmac-sha256-algorithm-security"
  expiration: 1800000  # 30분 (밀리초)

redis:
  host: localhost
  port: 6379